/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.panels;

import java.awt.Graphics;
import java.util.ArrayList;

/**
 *
 * @author Emilio
 */
public class PnlGrafTopProductos extends javax.swing.JPanel {
    private boolean notGraph = true;
    private final ArrayList<String> nombres;
    private final ArrayList<Double> montos;

    /**
     * Creates new form PnlGrafTopProductos
     */
    public PnlGrafTopProductos() {
        initComponents();
        nombres = new ArrayList<>();
        montos = new ArrayList<>();
    }
    
    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        if(notGraph) return;
        nombres.clear();
        montos.clear();
        int mxSz = -190;
        
        g.drawString("1. "+nombres.get(0), 20, 130);
        g.drawString("1", 220, 220);
        g.drawString("2. "+nombres.get(1), 20, 160);
        g.drawString("2", 320, 220);
        g.drawString("3. "+nombres.get(2), 20, 190);
        g.drawString("3", 420, 220);
        
        Double tot = montos.get(0) + montos.get(1) + montos.get(2);
        
        g.fillRect(220, 200, 40, (int) (mxSz*montos.get(0)/tot));
        g.fillRect(320, 200, 40, (int) (mxSz*montos.get(1)/tot));
        g.fillRect(420, 200, 40, (int) (mxSz*montos.get(2)/tot));
        //drawgraf
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dtchIni = new com.toedter.calendar.JDateChooser();
        lblFechaIni = new javax.swing.JLabel();
        lblFechaFin = new javax.swing.JLabel();
        dtchFin = new com.toedter.calendar.JDateChooser();
        btnObtenerGraf = new javax.swing.JButton();

        lblFechaIni.setText("Fecha Inicio:");

        lblFechaFin.setText("Fecha Fin:");

        btnObtenerGraf.setText("Graficar Datos");
        btnObtenerGraf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnObtenerGrafMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaIni)
                            .addComponent(lblFechaFin))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtchFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtchIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnObtenerGraf))
                .addContainerGap(352, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dtchIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaIni))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFechaFin)
                    .addComponent(dtchFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnObtenerGraf)
                .addContainerGap(145, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnObtenerGrafMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnObtenerGrafMouseClicked
        // TODO add your handling code here:
        notGraph = false;
        this.repaint();
    }//GEN-LAST:event_btnObtenerGrafMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObtenerGraf;
    private com.toedter.calendar.JDateChooser dtchFin;
    private com.toedter.calendar.JDateChooser dtchIni;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaIni;
    // End of variables declaration//GEN-END:variables
}
