/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.panels;

import Controlador.PayeeBL;
import Modelo.Payee;
import java.awt.Color;
import java.awt.Graphics;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Emilio
 */
public class PnlGrafTopComisionistas extends javax.swing.JPanel {
    private final PayeeBL control;
    private ArrayList<Payee> lst;
    private final int szGraph;
    private Double tot;

    /**
     * Creates new form PnlGrafTopComisionistas
     */
    public PnlGrafTopComisionistas(String id) {
        initComponents();
        szGraph = 500;     
        control = new PayeeBL();
        lst = control.getPayees(id);
        if(lst.isEmpty()){
            JOptionPane.showMessageDialog(this, "Ocurrió un error en la carga de datos", "ERROR", HEIGHT);
            pnlNombres.setEnabled(false);
            pnlGrafico.setEnabled(false);
        }else{
            ldData();
        }
    }
    
    public void ldData(){
        DefaultListModel<String> mdl = new DefaultListModel<String>();
        int i=0;
        tot=0.0;
        for(Payee elem:lst){
            i++;
            mdl.addElement("["+i+"]: "+elem.getNombre() + " " + elem.getApellidoPaterno());
            tot+=elem.getMonto();
        }
        lstNombres.setModel(mdl);
//        pntGraf();
    }
    
    private void pntGraf(){
    
        Graphics pnlG = pnlGrafico.getGraphics();
        int lim = 20;
        int y = 120;
        ArrayList<Color> lstClr = new ArrayList<>();
        lstClr.add(Color.blue);
        lstClr.add(Color.green);
        lstClr.add(Color.red);
        DecimalFormat df = new DecimalFormat("#.##"); 
        pnlG.drawRect(290, 50, 185, 190);
        pnlG.drawString("Leyenda", 290, y-80);
        pnlG.drawString("Nombre", 335, y-25 );
        pnlG.drawString("Monto (S/.)", 415, y-25);
        for(int i = 0; i < lst.size(); i++){
            
            pnlG.setColor(lstClr.get(i));
            pnlG.fillRect(295, y-10, 20, 20);
                pnlG.fillArc(40, 25, 220, 250, lim-20, 360-lim+20);
            lim += (int) (360*lst.get(i).getMonto()/tot);
            pnlG.setColor(Color.black);
            pnlG.drawString(lst.get(i).getNombre() + " " + lst.get(i).getApellidoPaterno(), 320, y);
            double monto = lst.get(i).getMonto();
            pnlG.drawString(df.format(monto), 435, y);
            y += 30;
        }
        pnlG.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNombres = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstNombres = new javax.swing.JList<>();
        pnlGrafico = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblInstruct = new javax.swing.JLabel();

        pnlNombres.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombres:"));

        jScrollPane1.setViewportView(lstNombres);

        javax.swing.GroupLayout pnlNombresLayout = new javax.swing.GroupLayout(pnlNombres);
        pnlNombres.setLayout(pnlNombresLayout);
        pnlNombresLayout.setHorizontalGroup(
            pnlNombresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNombresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlNombresLayout.setVerticalGroup(
            pnlNombresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNombresLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlGrafico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlGrafico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlGraficoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 183, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlGraficoLayout = new javax.swing.GroupLayout(pnlGrafico);
        pnlGrafico.setLayout(pnlGraficoLayout);
        pnlGraficoLayout.setHorizontalGroup(
            pnlGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGraficoLayout.createSequentialGroup()
                .addContainerGap(292, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlGraficoLayout.setVerticalGroup(
            pnlGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGraficoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblInstruct.setText("Click en el panel de la derecha.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInstruct)
                    .addComponent(pnlNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(pnlGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInstruct)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pnlGraficoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGraficoMouseClicked
        // TODO add your handling code here:
        pntGraf();
    }//GEN-LAST:event_pnlGraficoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInstruct;
    private javax.swing.JList<String> lstNombres;
    private javax.swing.JPanel pnlGrafico;
    private javax.swing.JPanel pnlNombres;
    // End of variables declaration//GEN-END:variables
}
