/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.panels;

import Controlador.ProductoBL;
import java.awt.Graphics;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Emilio
 */
public class PnlGrafTopProductos extends javax.swing.JPanel {
    private final ProductoBL prodBL;
    private boolean graph = false;
    private final ArrayList<String> nombres;
    private final ArrayList<Double> montos;

    /**
     * Creates new form PnlGrafTopProductos
     */
    public PnlGrafTopProductos() {
        initComponents();
        prodBL = new ProductoBL();
        nombres = new ArrayList<>();
        montos = new ArrayList<>();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dtchIni = new com.toedter.calendar.JDateChooser();
        lblFechaIni = new javax.swing.JLabel();
        lblFechaFin = new javax.swing.JLabel();
        dtchFin = new com.toedter.calendar.JDateChooser();
        btnObtenerGraf = new javax.swing.JButton();

        lblFechaIni.setText("Fecha Inicio:");

        lblFechaFin.setText("Fecha Fin:");

        btnObtenerGraf.setText("Graficar Datos");
        btnObtenerGraf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnObtenerGrafMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFechaIni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dtchIni, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(dtchFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnObtenerGraf))
                .addContainerGap(314, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dtchIni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFechaIni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dtchFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnObtenerGraf)
                .addContainerGap(145, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnObtenerGrafMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnObtenerGrafMouseClicked
        // TODO add your handling code here:
        
        nombres.clear();
        montos.clear();
        this.paint(this.getGraphics());
        if(!prodBL.productosDestacados(nombres, montos, dtchIni.getDate(), dtchFin.getDate())){
            JOptionPane.showMessageDialog(this, "Error de fechas o base de datos.");
            graph=false;
        }else{
            Graphics g = this.getGraphics();
            int mxSz = 210;

            g.drawString("1. "+nombres.get(0), 20, 160);
            g.drawString("1", 270, 220);
            g.drawString("2. "+nombres.get(1), 20, 190);
            g.drawString("2", 380, 220);
            g.drawString("3. "+nombres.get(2), 20, 220);
            g.drawString("3", 490, 220);

            Double tot = montos.get(0) + montos.get(1) + montos.get(2);
            int v1 = (int) (mxSz*montos.get(0)/tot);
            int v2 = (int) (mxSz*montos.get(1)/tot);
            int v3 = (int) (mxSz*montos.get(2)/tot);
            g.fillRect(280, 210-v1, 40, v1);
            g.fillRect(380, 210-v2, 40, v2);
            g.fillRect(480, 210-v3, 40, v3);
            g.dispose();
        }
    }//GEN-LAST:event_btnObtenerGrafMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObtenerGraf;
    private com.toedter.calendar.JDateChooser dtchFin;
    private com.toedter.calendar.JDateChooser dtchIni;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaIni;
    // End of variables declaration//GEN-END:variables
}
