/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author Emilio
 */
public class FrmMainOptionsAdmin extends javax.swing.JDialog {

    private FrmAdministrarCuenta administrarCuenta;
    private FrmAnadirNoticia addNoticia;
    private FrmReportarInfraccion reportarInfraccion;
    private FrmRealizarBackup backup;
    private FrmPapeleraReciclaje papelera;
    private FrmVerMapa mapa;
    private FrmVerRecomendaciones verRecom;
    private FrmNoticias verNoticia;
    private FrmVisualizarInfraccion visualizarInfracciones;
    private FrmVisualizarUsuario usuario;
    /**
     * Creates new form NewJDialog
     */
    public FrmMainOptionsAdmin(java.awt.Frame parent, boolean modal, String user) {
        super(parent, modal);
        initComponents();
        this.setTitle("GESCOM TDP - " + user);
        
        administrarCuenta = null;
        addNoticia = null;
        reportarInfraccion = null;
        backup = null;
        papelera = null;
        mapa = null;
        verRecom = null;
        verNoticia = null;
        visualizarInfracciones = null;
        usuario = null;
    }
    
    private void getUserForm(String str){
        if(usuario != null){
            try{
                usuario.setClosed(true);
            }catch(Exception e){
                System.out.println(e.getMessage());
            }
            usuario.dispose();
        }
        usuario = new FrmVisualizarUsuario(str);
        usuario.setClosable(true);
        dskPnPrincipal.add(usuario);usuario.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskPnPrincipal = new javax.swing.JDesktopPane();
        pnlComisionistas = new javax.swing.JPanel();
        lblComDestac = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlNoticia = new javax.swing.JPanel();
        lblNoticias = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAdministracion = new javax.swing.JMenu();
        menuiGestUsuario = new javax.swing.JMenuItem();
        menuiGestOrden = new javax.swing.JMenuItem();
        menuiGestProducto = new javax.swing.JMenuItem();
        menuCalculo = new javax.swing.JMenu();
        menuiFijarPeriodo = new javax.swing.JMenuItem();
        menuiCalcularComisiones = new javax.swing.JMenuItem();
        menuVisualizacion = new javax.swing.JMenu();
        menuiComisiones = new javax.swing.JMenuItem();
        menuiProductos = new javax.swing.JMenuItem();
        menuiCanalesVenta = new javax.swing.JMenuItem();
        menuPersonalCargo = new javax.swing.JMenu();
        menuiJefes = new javax.swing.JMenuItem();
        menuiComisionistas = new javax.swing.JMenuItem();
        menuiGerentes = new javax.swing.JMenuItem();
        menuiInfracciones = new javax.swing.JMenuItem();
        menuiNoticias = new javax.swing.JMenuItem();
        menuOtros = new javax.swing.JMenu();
        menuiRecomendaciones = new javax.swing.JMenuItem();
        menuiActMap = new javax.swing.JMenuItem();
        menuiPapelera = new javax.swing.JMenuItem();
        menuiBackup = new javax.swing.JMenuItem();
        menuiReportInfraccion = new javax.swing.JMenuItem();
        menuiAnadirNoticias = new javax.swing.JMenuItem();
        menuiVerMapa = new javax.swing.JMenuItem();
        menuCuenta = new javax.swing.JMenu();
        menuiCambDatPer = new javax.swing.JMenuItem();
        menuiCambContr = new javax.swing.JMenuItem();
        menuCerrar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblComDestac.setText("Comisionistas Destacados");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Comisionista", "Jefe Directo"
            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout pnlComisionistasLayout = new javax.swing.GroupLayout(pnlComisionistas);
        pnlComisionistas.setLayout(pnlComisionistasLayout);
        pnlComisionistasLayout.setHorizontalGroup(
            pnlComisionistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComisionistasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblComDestac)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlComisionistasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlComisionistasLayout.setVerticalGroup(
            pnlComisionistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComisionistasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblComDestac)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblNoticias.setText("Noticias");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout pnlNoticiaLayout = new javax.swing.GroupLayout(pnlNoticia);
        pnlNoticia.setLayout(pnlNoticiaLayout);
        pnlNoticiaLayout.setHorizontalGroup(
            pnlNoticiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNoticiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNoticiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addGroup(pnlNoticiaLayout.createSequentialGroup()
                        .addComponent(lblNoticias)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlNoticiaLayout.setVerticalGroup(
            pnlNoticiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNoticiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNoticias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        dskPnPrincipal.setLayer(pnlComisionistas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskPnPrincipal.setLayer(pnlNoticia, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dskPnPrincipalLayout = new javax.swing.GroupLayout(dskPnPrincipal);
        dskPnPrincipal.setLayout(dskPnPrincipalLayout);
        dskPnPrincipalLayout.setHorizontalGroup(
            dskPnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dskPnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlNoticia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                .addComponent(pnlComisionistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        dskPnPrincipalLayout.setVerticalGroup(
            dskPnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dskPnPrincipalLayout.createSequentialGroup()
                .addContainerGap(322, Short.MAX_VALUE)
                .addGroup(dskPnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlComisionistas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNoticia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        menuAdministracion.setText("Administración");

        menuiGestUsuario.setText("Gestionar Usuarios");
        menuAdministracion.add(menuiGestUsuario);

        menuiGestOrden.setText("Gestionar Ordenes");
        menuAdministracion.add(menuiGestOrden);

        menuiGestProducto.setText("Gestionar Productos");
        menuAdministracion.add(menuiGestProducto);

        jMenuBar1.add(menuAdministracion);

        menuCalculo.setText("Cálculo");

        menuiFijarPeriodo.setText("Fijar periodo de cálculo");
        menuCalculo.add(menuiFijarPeriodo);

        menuiCalcularComisiones.setText("Calcular Comisiones");
        menuCalculo.add(menuiCalcularComisiones);

        jMenuBar1.add(menuCalculo);

        menuVisualizacion.setText("Visualización");

        menuiComisiones.setText("Comisiones");
        menuVisualizacion.add(menuiComisiones);

        menuiProductos.setText("Productos");
        menuVisualizacion.add(menuiProductos);

        menuiCanalesVenta.setText("Canales de Venta");
        menuVisualizacion.add(menuiCanalesVenta);

        menuPersonalCargo.setText("Personal a Cargo");

        menuiJefes.setText("Jefes");
        menuiJefes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuiJefesActionPerformed(evt);
            }
        });
        menuPersonalCargo.add(menuiJefes);

        menuiComisionistas.setText("Comisionistas");
        menuiComisionistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuiComisionistasActionPerformed(evt);
            }
        });
        menuPersonalCargo.add(menuiComisionistas);

        menuiGerentes.setText("Gerentes");
        menuiGerentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuiGerentesActionPerformed(evt);
            }
        });
        menuPersonalCargo.add(menuiGerentes);

        menuVisualizacion.add(menuPersonalCargo);

        menuiInfracciones.setText("Infracciones");
        menuiInfracciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuiInfraccionesActionPerformed(evt);
            }
        });
        menuVisualizacion.add(menuiInfracciones);

        menuiNoticias.setText("Noticias");
        menuiNoticias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuiNoticiasActionPerformed(evt);
            }
        });
        menuVisualizacion.add(menuiNoticias);

        jMenuBar1.add(menuVisualizacion);

        menuOtros.setText("Otros");

        menuiRecomendaciones.setText("Enviar Recomendaciones");
        menuiRecomendaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuiRecomendacionesActionPerformed(evt);
            }
        });
        menuOtros.add(menuiRecomendaciones);

        menuiActMap.setText("Actualizar Mapa");
        menuiActMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuiActMapActionPerformed(evt);
            }
        });
        menuOtros.add(menuiActMap);

        menuiPapelera.setText("Papelera de Reciclaje");
        menuiPapelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuiPapeleraActionPerformed(evt);
            }
        });
        menuOtros.add(menuiPapelera);

        menuiBackup.setText("Backup");
        menuiBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuiBackupActionPerformed(evt);
            }
        });
        menuOtros.add(menuiBackup);

        menuiReportInfraccion.setText("Reportar Infracción");
        menuiReportInfraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuiReportInfraccionActionPerformed(evt);
            }
        });
        menuOtros.add(menuiReportInfraccion);

        menuiAnadirNoticias.setText("Añadir Noticias");
        menuiAnadirNoticias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuiAnadirNoticiasActionPerformed(evt);
            }
        });
        menuOtros.add(menuiAnadirNoticias);

        menuiVerMapa.setText("Ver Mapa");
        menuOtros.add(menuiVerMapa);

        jMenuBar1.add(menuOtros);

        menuCuenta.setText("Mi Cuenta");

        menuiCambDatPer.setText("Cambiar Datos Personales");
        menuiCambDatPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuiCambDatPerActionPerformed(evt);
            }
        });
        menuCuenta.add(menuiCambDatPer);

        menuiCambContr.setText("Cambiar Contraseña");
        menuiCambContr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuiCambContrActionPerformed(evt);
            }
        });
        menuCuenta.add(menuiCambContr);

        jMenuBar1.add(menuCuenta);

        menuCerrar.setText("Cerrar Sesión");
        menuCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCerrarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuCerrar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPnPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPnPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCerrarMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_menuCerrarMouseClicked

    private void menuiCambContrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuiCambContrActionPerformed
        // TODO add your handling code here:
        FrmCambiarContrasena frm = new FrmCambiarContrasena(null, true);
        frm.setVisible(true);
        //.setVisible(false);
        frm.dispose();
    }//GEN-LAST:event_menuiCambContrActionPerformed

    private void menuiCambDatPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuiCambDatPerActionPerformed
        // TODO add your handling code here:
        if(administrarCuenta != null){
            try{
                administrarCuenta.setClosed(true);
            }catch(Exception e){
                System.out.println(e.getMessage());
            }
            administrarCuenta.dispose();
        }
        administrarCuenta = new FrmAdministrarCuenta();
        administrarCuenta.setClosable(true);
        dskPnPrincipal.add(administrarCuenta);
        //System.out.println(dskPnPrincipal.getAllFrames().length);
        administrarCuenta.setVisible(true);
    }//GEN-LAST:event_menuiCambDatPerActionPerformed

    private void menuiAnadirNoticiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuiAnadirNoticiasActionPerformed
        // TODO add your handling code here:
        if(addNoticia != null){
            try{
                addNoticia.setClosed(true);
            }catch(Exception e){
                System.out.println(e.getMessage());
            }
            addNoticia.dispose();
        }
        addNoticia = new FrmAnadirNoticia();
        addNoticia.setClosable(true);
        addNoticia.pack();
        dskPnPrincipal.add(addNoticia);
        addNoticia.setVisible(true);
    }//GEN-LAST:event_menuiAnadirNoticiasActionPerformed

    private void menuiReportInfraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuiReportInfraccionActionPerformed
        // TODO add your handling code here:
        if(reportarInfraccion != null){
            try{
                reportarInfraccion.setClosed(true);
            }catch(Exception ex){
                System.out.println(ex.getMessage());
            }
            reportarInfraccion.dispose();
        }
        reportarInfraccion = new FrmReportarInfraccion();
        reportarInfraccion.setClosable(true);
        reportarInfraccion.pack();
        dskPnPrincipal.add(reportarInfraccion);
        reportarInfraccion.setVisible(true);
    }//GEN-LAST:event_menuiReportInfraccionActionPerformed

    private void menuiBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuiBackupActionPerformed
        // TODO add your handling code here:
        if(backup != null){
            try{
                backup.setClosed(true);
            }catch(Exception ex){
                System.out.println(ex.getMessage());
            }
            backup.dispose();
        }
        backup = new FrmRealizarBackup();
        backup.setClosable(true);
        backup.pack();
        dskPnPrincipal.add(backup);
        backup.setVisible(true);
    }//GEN-LAST:event_menuiBackupActionPerformed

    private void menuiPapeleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuiPapeleraActionPerformed
        // TODO add your handling code here:
        if(papelera != null){
            try{
                papelera.setClosed(true);
            }catch(Exception ex){
                System.out.println(ex.getMessage());
            }
            papelera.dispose();
        }
        papelera = new FrmPapeleraReciclaje();
        papelera.setClosable(true);
        papelera.pack();
        dskPnPrincipal.add(papelera);
        papelera.setVisible(true);
    }//GEN-LAST:event_menuiPapeleraActionPerformed

    private void menuiActMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuiActMapActionPerformed
        // TODO add your handling code here:
        if(mapa != null){
            try{
                mapa.setClosed(true);
            }catch(Exception ex){
                System.out.println(ex.getMessage());
            }
            mapa.dispose();
        }
        mapa = new FrmVerMapa();
        mapa.setClosable(true);
        mapa.pack();
        dskPnPrincipal.add(mapa);
        mapa.setVisible(true);
    }//GEN-LAST:event_menuiActMapActionPerformed

    private void menuiRecomendacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuiRecomendacionesActionPerformed
        // TODO add your handling code here:
        if(verRecom != null){
            try{
                verRecom.setClosed(true);
            }catch(Exception ex){
                System.out.println(ex.getMessage());
            }
            verRecom.dispose();
        }
        verRecom = new FrmVerRecomendaciones();
        verRecom.setClosable(true);
        verRecom.pack();
        dskPnPrincipal.add(verRecom);
        verRecom.setVisible(true);
    }//GEN-LAST:event_menuiRecomendacionesActionPerformed

    private void menuiNoticiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuiNoticiasActionPerformed
        // TODO add your handling code here:
        if(verNoticia != null){
            try{
                verNoticia.setClosed(true);
            }catch(Exception ex){
                System.out.println(ex.getMessage());
            }
            verNoticia.dispose();
        }
        verNoticia = new FrmNoticias();
        verNoticia.setClosable(true);
        verNoticia.pack();
        dskPnPrincipal.add(verNoticia);
        verNoticia.setVisible(true);
    }//GEN-LAST:event_menuiNoticiasActionPerformed

    private void menuiInfraccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuiInfraccionesActionPerformed
        // TODO add your handling code here:
        if(visualizarInfracciones != null){
            try{
                visualizarInfracciones.setClosed(true);
            }catch(Exception ex){
                System.out.println(ex.getMessage());
            }
            visualizarInfracciones.dispose();
        }
        visualizarInfracciones = new FrmVisualizarInfraccion();
        visualizarInfracciones.setClosable(true);
        visualizarInfracciones.pack();
        dskPnPrincipal.add(visualizarInfracciones);
        visualizarInfracciones.setVisible(true);
    }//GEN-LAST:event_menuiInfraccionesActionPerformed

    private void menuiGerentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuiGerentesActionPerformed
        // TODO add your handling code here:
        getUserForm("Gerente");
    }//GEN-LAST:event_menuiGerentesActionPerformed

    private void menuiComisionistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuiComisionistasActionPerformed
        // TODO add your handling code here:
        getUserForm("Comisionista");
    }//GEN-LAST:event_menuiComisionistasActionPerformed

    private void menuiJefesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuiJefesActionPerformed
        // TODO add your handling code here:
        getUserForm("Jefe");
    }//GEN-LAST:event_menuiJefesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMainOptionsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMainOptionsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMainOptionsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMainOptionsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmMainOptionsAdmin dialog = new FrmMainOptionsAdmin(new javax.swing.JFrame(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskPnPrincipal;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblComDestac;
    private javax.swing.JLabel lblNoticias;
    private javax.swing.JMenu menuAdministracion;
    private javax.swing.JMenu menuCalculo;
    private javax.swing.JMenu menuCerrar;
    private javax.swing.JMenu menuCuenta;
    private javax.swing.JMenu menuOtros;
    private javax.swing.JMenu menuPersonalCargo;
    private javax.swing.JMenu menuVisualizacion;
    private javax.swing.JMenuItem menuiActMap;
    private javax.swing.JMenuItem menuiAnadirNoticias;
    private javax.swing.JMenuItem menuiBackup;
    private javax.swing.JMenuItem menuiCalcularComisiones;
    private javax.swing.JMenuItem menuiCambContr;
    private javax.swing.JMenuItem menuiCambDatPer;
    private javax.swing.JMenuItem menuiCanalesVenta;
    private javax.swing.JMenuItem menuiComisiones;
    private javax.swing.JMenuItem menuiComisionistas;
    private javax.swing.JMenuItem menuiFijarPeriodo;
    private javax.swing.JMenuItem menuiGerentes;
    private javax.swing.JMenuItem menuiGestOrden;
    private javax.swing.JMenuItem menuiGestProducto;
    private javax.swing.JMenuItem menuiGestUsuario;
    private javax.swing.JMenuItem menuiInfracciones;
    private javax.swing.JMenuItem menuiJefes;
    private javax.swing.JMenuItem menuiNoticias;
    private javax.swing.JMenuItem menuiPapelera;
    private javax.swing.JMenuItem menuiProductos;
    private javax.swing.JMenuItem menuiRecomendaciones;
    private javax.swing.JMenuItem menuiReportInfraccion;
    private javax.swing.JMenuItem menuiVerMapa;
    private javax.swing.JPanel pnlComisionistas;
    private javax.swing.JPanel pnlNoticia;
    // End of variables declaration//GEN-END:variables
}
