/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Emilio
 */
public class frmMainOptionsAdmin extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public frmMainOptionsAdmin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("GESCOM TDP");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuAdministracion = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuCalculo = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        menuVisualizacion = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        menuOtros = new javax.swing.JMenu();
        menuEnvRec = new javax.swing.JMenuItem();
        menuActMap = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        menuCuenta = new javax.swing.JMenu();
        menModDatos = new javax.swing.JMenuItem();
        menuCerrar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 400));

        menuAdministracion.setText("Administración");

        jMenuItem1.setText("jMenuItem1");
        menuAdministracion.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        menuAdministracion.add(jMenuItem2);

        jMenuItem3.setText("jMenuItem3");
        menuAdministracion.add(jMenuItem3);

        jMenuBar1.add(menuAdministracion);

        menuCalculo.setText("Cálculo");

        jMenuItem4.setText("jMenuItem4");
        menuCalculo.add(jMenuItem4);

        jMenuItem5.setText("jMenuItem5");
        menuCalculo.add(jMenuItem5);

        jMenuBar1.add(menuCalculo);

        menuVisualizacion.setText("Visualización");

        jMenuItem6.setText("jMenuItem6");
        menuVisualizacion.add(jMenuItem6);

        jMenuItem7.setText("jMenuItem7");
        menuVisualizacion.add(jMenuItem7);

        jMenuItem8.setText("jMenuItem8");
        menuVisualizacion.add(jMenuItem8);

        jMenuItem9.setText("jMenuItem9");
        menuVisualizacion.add(jMenuItem9);

        jMenuItem10.setText("jMenuItem9");
        menuVisualizacion.add(jMenuItem10);

        jMenuItem11.setText("jMenuItem9");
        menuVisualizacion.add(jMenuItem11);

        jMenuBar1.add(menuVisualizacion);

        menuOtros.setText("Otros");

        menuEnvRec.setText("Enviar recomendaciones");
        menuOtros.add(menuEnvRec);

        menuActMap.setText("Actualizar Mapa");
        menuOtros.add(menuActMap);

        jMenuItem14.setText("jMenuItem9");
        menuOtros.add(jMenuItem14);

        jMenuItem15.setText("jMenuItem9");
        menuOtros.add(jMenuItem15);

        jMenuItem16.setText("jMenuItem9");
        menuOtros.add(jMenuItem16);

        jMenuItem17.setText("jMenuItem9");
        menuOtros.add(jMenuItem17);

        jMenuBar1.add(menuOtros);

        menuCuenta.setText("Mi Cuenta");

        menModDatos.setText("Modificar datos");
        menuCuenta.add(menModDatos);

        jMenuBar1.add(menuCuenta);

        menuCerrar.setText("Cerrar Sesión");
        menuCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCerrarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuCerrar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCerrarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_menuCerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMainOptionsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMainOptionsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMainOptionsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMainOptionsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmMainOptionsAdmin dialog = new frmMainOptionsAdmin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem menModDatos;
    private javax.swing.JMenuItem menuActMap;
    private javax.swing.JMenu menuAdministracion;
    private javax.swing.JMenu menuCalculo;
    private javax.swing.JMenu menuCerrar;
    private javax.swing.JMenu menuCuenta;
    private javax.swing.JMenuItem menuEnvRec;
    private javax.swing.JMenu menuOtros;
    private javax.swing.JMenu menuVisualizacion;
    // End of variables declaration//GEN-END:variables
}
