package Vista;
import java.io.*;

public class FrmNoticias extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmNoticias
     */
    public FrmNoticias() {
        initComponents();
        try{
            inicializarArchivo();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        this.txtANoticias.setEditable(false);
    }

    private void inicializarArchivo() throws Exception
    {
        FileReader archNoticias = new FileReader("./archivos/archNoticias.dat");
        BufferedReader rd = new BufferedReader(archNoticias);

        String data = "";
        while (true)
        {
            String linea = rd.readLine();
            if (linea == null) break;
            linea += "\n";
            data += linea;
        }

        txtANoticias.setText(data);
        rd.close();
        archNoticias.close();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNoticias = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtANoticias = new javax.swing.JTextArea();
        btnRegresar = new javax.swing.JButton();

        lblNoticias.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblNoticias.setText("Noticias recientes:");

        txtANoticias.setColumns(20);
        txtANoticias.setLineWrap(true);
        txtANoticias.setRows(5);
        jScrollPane1.setViewportView(txtANoticias);

        btnRegresar.setText("Regresar");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNoticias)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNoticias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
        try{
            this.setClosed(true);
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnRegresarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNoticias;
    private javax.swing.JTextArea txtANoticias;
    // End of variables declaration//GEN-END:variables
}
