package Vista;

import Controlador.PayeeBL;
import Modelo.Payee;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

public class FrmVisualizarUsuario extends javax.swing.JInternalFrame {

    private List<Payee> listaOrig;
    private PayeeBL logicaNegocio;
    private String puesto;
    
    public FrmVisualizarUsuario(String cargoLista, String idPayee, String puesto) {
        initComponents();
        cmbCampo.addItem("ID");
        cmbCampo.addItem("Nombre");
        cmbCampo.addItem("Distrito");
        cmbCampo.addItem("Cargo");
        
        this.puesto = puesto;
        logicaNegocio = new PayeeBL();
        
        
        listaOrig = new ArrayList<>();
        switch(this.puesto){
            case "ADMINISTRADOR":
                switch(cargoLista){
                    case "Gerente":
                        listaOrig = logicaNegocio.listarGerentes();
                        break;
                    case "Jefe":
                        listaOrig = logicaNegocio.listarJefes("ALL");
                        break;
                    case "Comisionista":
                        listaOrig = logicaNegocio.listarComisionistas("ALL");
                }
                break;
            case "GERENTE":
                switch(cargoLista){
                    case "Jefe":
                        listaOrig = logicaNegocio.listarJefes("ALL");
                        break;
                    case "Comisionista":
                        listaOrig = logicaNegocio.listarComisionistas("ALL");
                }
                break;
            case "JEFE":
                switch(cargoLista){
                    case "Comisionista":
                        listaOrig = logicaNegocio.listarComisionistas(idPayee);
                }
                break;
            default:
                JOptionPane.showMessageDialog(null, "No se econtraron resultados", "Lista vacía", JOptionPane.WARNING_MESSAGE);
                break;
        }
        tblDatosTrabajador.setAutoResizeMode(tblDatosTrabajador.AUTO_RESIZE_ALL_COLUMNS);
        
        //setColsTbl((DefaultTableModel) this.tblDatosTrabajador.getModel(), new String[]{"idPayee","DNI","Nombre","Apellido Paterno","Apellido Materno","Correo","Usuario","Distrito","Cargo"});   
//        tblDatosTrabajador.getParent().addComponentListener(new ComponentAdapter() {
//            @Override
//            public void componentResized(final ComponentEvent e) {
//                if (tblDatosTrabajador.getPreferredSize().width < tblDatosTrabajador.getParent().getWidth()) {
//                    tblDatosTrabajador.setAutoResizeMode(tblDatosTrabajador.AUTO_RESIZE_ALL_COLUMNS);
//                } else {
//                    tblDatosTrabajador.setAutoResizeMode(tblDatosTrabajador.AUTO_RESIZE_OFF);
//                }
//            }
//        });
        
        
        DefaultTableModel modelo = (DefaultTableModel) this.tblDatosTrabajador.getModel();
        Object[] fila = new Object [10];
        for (int i=0;i<listaOrig.size();i++){
            
            fila[0] = listaOrig.get(i).getIdTrabajador();
            fila[1] = listaOrig.get(i).getDni();
            fila[2] = listaOrig.get(i).getNombre();
            fila[3] = listaOrig.get(i).getApellidoPaterno();
            fila[4] = listaOrig.get(i).getApellidoMaterno();
            fila[5] = listaOrig.get(i).getEmail();
            fila[6] = listaOrig.get(i).getUserName();
            fila[7] = listaOrig.get(i).getDistrito();
            fila[8] = listaOrig.get(i).getCargo();
            modelo.addRow(fila);
        }
    }

//    private void setColsTbl(DefaultTableModel tbl, String[] cols){
//        for(int i = 0; i < cols.length; i++){
//            tbl.addColumn(cols[i]);
//        }
//        //tblDatosTrabajador.getColumn(0).setpr(tblDatosTrabajador.getColumnName(i).length()*10+20);
//    }
    
    private void setItemsCmb(DefaultComboBoxModel lst, String[] items){
        for(int i = 0; i < items.length; i++){
            lst.addElement(items[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCampo = new javax.swing.JLabel();
        cmbCampo = new javax.swing.JComboBox<>();
        btnRegresar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        pnlSelect = new javax.swing.JPanel();
        txtDato = new javax.swing.JTextField();
        lblDato = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDatosTrabajador = new javax.swing.JTable();

        lblCampo.setText("Ingrese campo para buscar");

        btnRegresar.setText("Regresar");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        lblDato.setText("Ingrese Dato");

        javax.swing.GroupLayout pnlSelectLayout = new javax.swing.GroupLayout(pnlSelect);
        pnlSelect.setLayout(pnlSelectLayout);
        pnlSelectLayout.setHorizontalGroup(
            pnlSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDato)
                    .addGroup(pnlSelectLayout.createSequentialGroup()
                        .addComponent(lblDato)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlSelectLayout.setVerticalGroup(
            pnlSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSelectLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tblDatosTrabajador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DNI", "Nombre", "Apellido Paterno", "Apellido Materno", "E-mail", "Username", "Distrito", "Cargo"
            }
        ));
        jScrollPane2.setViewportView(tblDatosTrabajador);
        if (tblDatosTrabajador.getColumnModel().getColumnCount() > 0) {
            tblDatosTrabajador.getColumnModel().getColumn(0).setMaxWidth(80);
            tblDatosTrabajador.getColumnModel().getColumn(5).setMinWidth(120);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCampo)
                                .addGap(48, 48, 48)
                                .addComponent(cmbCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnRegresar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampo)
                    .addComponent(cmbCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addGap(49, 49, 49)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
        try{
            this.setClosed(true);
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbCampo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCampo;
    private javax.swing.JLabel lblDato;
    private javax.swing.JPanel pnlSelect;
    private javax.swing.JTable tblDatosTrabajador;
    private javax.swing.JTextField txtDato;
    // End of variables declaration//GEN-END:variables
}
